llm:
  provider: volcengine
  api_key: "****"
  model: ep-20250417174840-6c94l
  endpoint: https://ark.cn-beijing.volces.com/api/v3
  temperature: 0.2
  max_tokens: 2048
  verify_ssl: false # 添加此行以禁用 SSL 验证 (仅用于测试)
security:
  allow_bash: false
  allow_file_write: true
  allow_file_edit: true
  confirm_high_risk: true
tools:
  enabled:
  - FileRead
  - FileWrite
  - FileEdit
  - Glob
  - Grep
  - Ls
rules:
  type: 
  path:
