# .github/workflows/publish-to-pypi.yml
name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a specific version if needed, e.g., '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        # Install project dependencies if build requires them
        # pip install -r requirements.txt # Uncomment if needed
    - name: Build package
      run: python -m build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # Use PyPI API token stored in GitHub secrets
        # Go to your repository's settings > Secrets and variables > Actions > New repository secret
        # Name: PYPI_API_TOKEN
        # Value: Your PyPI API token (pypi-...)
        # Alternatively, use trusted publishing (recommended)
        # See: https://docs.pypi.org/trusted-publishers/
        # If using trusted publishing, remove the 'password' field below
        # password: ${{ secrets.PYPI_API_TOKEN }}
        # For trusted publishing, configure PyPI first, then this action will use OIDC.
        # Ensure your PyPI project is configured for trusted publishing with GitHub Actions.
        # The 'id-token: write' permission above is required for trusted publishing.
        # If not using trusted publishing, uncomment the 'password' line and comment out the permission.
        # repository_url: https://test.pypi.org/legacy/ # Uncomment for TestPyPI