# .github/workflows/publish-to-pypi.yml
name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a specific version if needed, e.g., '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        # Install project dependencies if build requires them
        # pip install -r requirements.txt # Uncomment if needed
    - name: Build package
      run: python -m build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # Trusted publishing is configured via permissions (id-token: write)
      # No 'with' parameters needed for standard PyPI publishing.